### PR TITLE
Updating Gradle to 6.6.1. Resolves GoogleCloudPlatform/artifact-regis…

### PR DESCRIPTION
**Pull request by keith-miller**
…try-maven-tools/35

### CODE REVIEW

**Comment by keith-miller** [comment]
@googlebot I signed it!

**Comment by keith-miller** [comment]
Hey, just trying to get the plugin upgraded to the latest Gradle, version 6.6.1 so that my team can be unblocked. Thanks

**Comment by lindsayismith** [comment]
I think that https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools/pull/37 might be a better option so that it works for both versions of Gradle.  I'm going to approve that one, and if it's still an issue we can revisit.

**Comment by keith-miller** [comment]
Works for me! Thanks

**Comment by lindsayismith** [comment]
Hi Keith,

Plumpy wrote a PR that should add support for 6.6 while maintaining
compatibility with 6.5, I think that's preferable.  If should be merged
now, if you could test it I can cut a release.

**Comment by keith-miller** [comment]
@lindsayismith ok, I can give it a go later today. Thanks again.

**Pull request closed without merging**
