### PR TITLE
Fix the plugin under Gradle 6.6+

### PR DESCRIPTION
**Pull request by plumpy**
In Gradle 6.6 they introduced a breaking API change where they changed the return type of a method. So you get `NoSuchMethodException` when you use the plugin. We can't just compile against Gradle 6.6, however, because then you'll get the same exception when you run it under Gradle 6.5 or less.

So instead we need to use... reflection :sob:

### CODE REVIEW

**Review by lindsayismith — APPROVED** [review]

**Comment by lindsayismith** [comment]
Thanks Michael, much appreciated.

**Comment by keith-miller** [comment]
This works for me locally @lindsayismith. A release would be great! 

Thanks @plumpy

**Comment by lindsayismith** [comment]
Release is finished, you should be able to use version 2.1.1 now from maven
or gradle.

Lindsay

**Comment by keith-miller** [comment]
Thanks!

**Pull request merged**
