### PR TITLE
Fix to apply plugin to project buildscript

### LINKED ISSUE #40: Gradle: Not a supported repository protocol 'artifactregistry' in buildscript block
When using the Gradle plugin for Google Cloud Artifact Registry in the `buildscript` section of a `build.gradle.kts` / `build.gradle` file, the repository protocol `artifactregistry` is not found.

An example repo can be found [here](https://github.com/trietsch/gradle-gcp-artifact-registry). Clone the repository and run `./gradlew clean build`, and you'll be presented with the following error:

```
❯ ./gradlew clean build
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'gradle-artifact-registry'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Not a supported repository protocol 'artifactregistry': valid protocols are [http, https, file, gcs, s3, sftp]
```

Removing the `maven("artifactregistry://...")` from the `buildscript` section works, however, I need to get a `classpath` dependency for the `buildscript` from my Maven Artifact Registry that resides in my GCP project. It seems that the plugin is not applied in the `buildscript` section. I have not found a way to do this, am I doing something wrong?

### PR DESCRIPTION
**Pull request by loosebazooka**
This only is applied if the plugin is applied at the
settings level

Signed-off-by: Appu Goundan <appu@google.com>

fixes #40 I think

### CODE REVIEW

**Comment by chanseokoh** [comment]
> This only is applied if the plugin is applied at the settings level

Does this mean the user has to apply the plugin in `settings.xml` and only in the legacy way using `apply()` (and probably should remove the plugin from `plugins{ id "com.google.cloud.artifactregistry.gradle-plugin" }` in `build.gradle` too)? The doc should be updated too?

**Comment by loosebazooka** [comment]
I'm not sure that you can to apply a plugin from `mavenLocal()` in a `settings.xml`, at least I haven't successfully managed it.  But for a published plugin from the gradle, I think it might be fine?

**Comment by chanseokoh** [comment]
Sorry, what I meant is not about applying a snapshot version for testing.

What I was asking is that, assuming this is fixed and the artifact plugin published a new release with the fix, when a user wants to use `artifactregistry://...` in the `buildscript` block (as in the original issue #40), does the user have to apply the published plugin in `settings.xml` (because `plugins{}` cannot come before `buildscript {}`), or is it still possible to declare it in the usual way with the `plugins` block in `build.gradle`?

**Comment by loosebazooka** [comment]
Right, I'm not completely sure about a plugin that is available on the gradle plugin portal, but I think you can use the plugins block.

**Comment by loosebazooka** [comment]
Ah so it has to be applied in the settings.gradle to make modifications to a plugins buildscript.

**Comment by loosebazooka** [comment]
User verified it's working: https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools/issues/40#issuecomment-889146338

**Review by chanseokoh — APPROVED** [review]

**Review by Gridasov — APPROVED** [review]

**Comment by trietsch** [comment]
Will a release be published to Maven Central / Gradle plugins?

**Comment by trietsch** [comment]
@loosebazooka @Gridasov any idea when a release will be available on https://plugins.gradle.org ?

**Comment by yihanzhen** [comment]
@loosebazooka v2.1.2 is here: https://plugins.gradle.org/plugin/com.google.cloud.artifactregistry.gradle-plugin. Please let us know if that solves your problem!

**Comment by trietsch** [comment]
Awesome, thanks for notifying @yihanzhen! I'll give it a spin :)

**Comment by trietsch** [comment]
@yihanzhen @loosebazooka thanks for the work and the release, it's working. This'll clean up our Gradle build scripts :D

**Pull request merged**
